config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post 'users/index', to: "users#index"
  get 'users/approve/:iduser', to: "users#approve", as: 'approve'
  post 'users/approve/:iduser', to: "users#approve"

  devise_for :users
  resources :subconcepts
  get 'hour/index/:pro,:per', to: "hour#index", as: 'index'
  get 'periods_auto/index'
  get 'expenses/new/:per', to: "expenses#new", as: 'new_expense'

  resources :cards
  resources :workers
  resources :administrative_expenses
  resources :projects_users
  resources :expenses
  resources :concepts
  resources :periods
  resources :clients
  resources :tasks
  resources :projects
  resources :companies
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  post '/expenses/new/:per', to: "expenses#new"
  post '/hour/index/:pro,:per', to: "hour#index"
  post '/administrative_expenses/new', to: "administrative_expenses#new"
  post '/concepts', to: "concepts#index"


end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :worker
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/concept.rb
class Concept < ApplicationRecord
	
	enum type_concept: [:indefinido, :viatico, :administrativo]
    after_initialize :set_default_type_concept, :if => :new_record?

  
    def set_default_type_concept
    	self.type_concept ||= :indefinido
    end

	def self.names(idc)
		na = Concept.find(idc)
		nam = na.name 
	end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :period
  belongs_to :project
  belongs_to :concept
  belongs_to :worker

  enum payment_type: [:efectivo, :tarjeta]
  after_initialize :set_default_payment_type, :if => :new_record?

  
  def set_default_payment_type
    self.payment_type ||= :efectivo
  end

  def self.dia_mes(fecha)
  	dia = fecha.cwday
  	if dia == 1
  		day = "Lun"
  	elsif dia == 2
  		day = "Mar"
	  elsif dia == 3
  		day = "Mie"
	  elsif dia == 4
  		day = "Jue"
	  elsif dia == 5
  		day = "Vie"
	  elsif dia == 6
  		day = "Sab"
	  elsif dia == 7
  		day = "Dom"
  	end
  	return day	
  end

  def self.checked(x,y)
    if x == y
      return :checked
    end
  end

end

app/models/hours_project.rb
class HoursProject < ApplicationRecord
  belongs_to :worker
  belongs_to :period
  belongs_to :project


  def self.hours_day(idw,ppe,proy,day)
  	horareg = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>ppe,"hours_projects.project_id"=>proy,"hours_projects.worker_id"=>idw) 
    hl = horareg.length
    for i in 0..hl-1 do
    	fecha = horareg[i].day
    	if fecha.cwday==day
    		cons = HoursProject.find_by(period_id:ppe,project_id:proy,day:fecha,worker_id:idw)
    		res = cons.hours
    	end
    end
    return res		
  end

  def self.hours_total(proy,per)
    horatot = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>per,"hours_projects.project_id"=>proy) 
    total = horatot.sum(:hours)
  end

  def self.periods_total(proy)
    pertot = HoursProject.select(:period_id).distinct.where("hours_projects.project_id"=>proy)
    pertot.count(:period_id)
  end

  def self.hours_id(idw,ppe,proy,day)
    horareg = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>ppe,"hours_projects.project_id"=>proy,"hours_projects.worker_id"=>idw) 
    hl = horareg.length
    for i in 0..hl-1 do
      fecha = horareg[i].day
      if fecha.cwday==day
        cons = HoursProject.find_by(period_id:ppe,project_id:proy,day:fecha,worker_id:idw)
        res = cons.id
      end
    end
    return res    
  end
end

app/models/period.rb
class Period < ApplicationRecord

	def self.periodo(per)
		perinf = Period.find(per)
		"#{perinf.date_start.strftime("%v")} "  " al "  " #{perinf.date_end.strftime("%v")}"
	end

	def periodosAnual
    	Period.order(:date_start).find_by(year: 2016)
	end
  	def periodoRango
	    fInicio = Date.strptime("#{date_start}", "%Y-%m-%d")
	    fIni = fInicio.to_formatted_s(:short)
	    fFinal = Date.strptime("#{date_end}", "%Y-%m-%d")
	    fFin = fFinal.to_formatted_s(:short)
	    "#{fIni} - #{fFin}"
  	end

    def self.periodosAnualCombo
	  	fInicio = Time.now - 2.month
	  	fFin 	= Time.now
	  	Period.where(["date_start >= '%s' and date_end <= '%s'", fInicio, fFin]).order(:date_start)
	end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company

	def self.names(idp)
		na = Project.find(idp)
		nam = na.name
	end
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :worker
  belongs_to :project
end

app/models/subconcept.rb
class Subconcept < ApplicationRecord
  belongs_to :concept
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :worker
end

app/models/user.rb
class User < ApplicationRecord
	has_one :worker
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  enum roles: [:user_default, :admin]
  after_initialize :set_default_roles, :if => :new_record?

  
  def set_default_roles
    self.roles ||= :user_default
  end

end

app/models/worker.rb
class Worker < ApplicationRecord
	belongs_to :user, optional: true
	has_attached_file :photo, styles:{thumb:"800x600", mini:"500x300"}
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

	def self.photos(idworker)
		pho = Worker.find(idworker)
		phot = pho.photo
	end

	def self.names(idworker)
		na = Worker.find(idworker)
		nam = na.name 
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :accesscontroller

  def accesscontroller
    if current_user.roles =="user_default"
      respond_to do |format|
          format.html {redirect_to welcome_index_path,notice: '' }
          format.js
      end
    end
  end


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :project_id, :status, :worker_id, :start_date, :due_date)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/hour_helper.rb
module HourHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="field">
    <%= f.label :worker_id %>
    <%= f.text_field :worker_id %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_select :due_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th>Status</th>
      <th>User</th>
      <th>Start date</th>
      <th>Due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.project %></td>
        <td><%= task.status %></td>
        <td><%= task.worker %></td>
        <td><%= task.start_date %></td>
        <td><%= task.due_date %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.worker %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>