config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post 'users/index', to: "users#index"
  get 'users/approve/:iduser', to: "users#approve", as: 'approve'
  post 'users/approve/:iduser', to: "users#approve"

  devise_for :users
  resources :subconcepts
  get 'hour/index/:pro,:per', to: "hour#index", as: 'index'
  get 'periods_auto/index'
  get 'expenses/new/:per', to: "expenses#new", as: 'new_expense'

  resources :cards
  resources :workers
  resources :administrative_expenses
  resources :projects_users
  resources :expenses
  resources :concepts
  resources :periods
  resources :clients
  resources :tasks
  resources :projects
  resources :companies
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  post '/expenses/new/:per', to: "expenses#new"
  post '/hour/index/:pro,:per', to: "hour#index"
  post '/administrative_expenses/new', to: "administrative_expenses#new"
  post '/concepts', to: "concepts#index"


end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :worker
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/concept.rb
class Concept < ApplicationRecord
	
	enum type_concept: [:indefinido, :viatico, :administrativo]
    after_initialize :set_default_type_concept, :if => :new_record?

  
    def set_default_type_concept
    	self.type_concept ||= :indefinido
    end

	def self.names(idc)
		na = Concept.find(idc)
		nam = na.name 
	end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :period
  belongs_to :project
  belongs_to :concept
  belongs_to :worker

  enum payment_type: [:efectivo, :tarjeta]
  after_initialize :set_default_payment_type, :if => :new_record?

  
  def set_default_payment_type
    self.payment_type ||= :efectivo
  end

  def self.dia_mes(fecha)
  	dia = fecha.cwday
  	if dia == 1
  		day = "Lun"
  	elsif dia == 2
  		day = "Mar"
	  elsif dia == 3
  		day = "Mie"
	  elsif dia == 4
  		day = "Jue"
	  elsif dia == 5
  		day = "Vie"
	  elsif dia == 6
  		day = "Sab"
	  elsif dia == 7
  		day = "Dom"
  	end
  	return day	
  end

  def self.checked(x,y)
    if x == y
      return :checked
    end
  end

end

app/models/hours_project.rb
class HoursProject < ApplicationRecord
  belongs_to :worker
  belongs_to :period
  belongs_to :project


  def self.hours_day(idw,ppe,proy,day)
  	horareg = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>ppe,"hours_projects.project_id"=>proy,"hours_projects.worker_id"=>idw) 
    hl = horareg.length
    for i in 0..hl-1 do
    	fecha = horareg[i].day
    	if fecha.cwday==day
    		cons = HoursProject.find_by(period_id:ppe,project_id:proy,day:fecha,worker_id:idw)
    		res = cons.hours
    	end
    end
    return res		
  end

  def self.hours_total(proy,per)
    horatot = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>per,"hours_projects.project_id"=>proy) 
    total = horatot.sum(:hours)
  end

  def self.periods_total(proy)
    pertot = HoursProject.select(:period_id).distinct.where("hours_projects.project_id"=>proy)
    pertot.count(:period_id)
  end

  def self.hours_id(idw,ppe,proy,day)
    horareg = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>ppe,"hours_projects.project_id"=>proy,"hours_projects.worker_id"=>idw) 
    hl = horareg.length
    for i in 0..hl-1 do
      fecha = horareg[i].day
      if fecha.cwday==day
        cons = HoursProject.find_by(period_id:ppe,project_id:proy,day:fecha,worker_id:idw)
        res = cons.id
      end
    end
    return res    
  end
end

app/models/period.rb
class Period < ApplicationRecord

	def self.periodo(per)
		perinf = Period.find(per)
		"#{perinf.date_start.strftime("%v")} "  " al "  " #{perinf.date_end.strftime("%v")}"
	end

	def periodosAnual
    	Period.order(:date_start).find_by(year: 2016)
	end
  	def periodoRango
	    fInicio = Date.strptime("#{date_start}", "%Y-%m-%d")
	    fIni = fInicio.to_formatted_s(:short)
	    fFinal = Date.strptime("#{date_end}", "%Y-%m-%d")
	    fFin = fFinal.to_formatted_s(:short)
	    "#{fIni} - #{fFin}"
  	end

    def self.periodosAnualCombo
	  	fInicio = Time.now - 2.month
	  	fFin 	= Time.now
	  	Period.where(["date_start >= '%s' and date_end <= '%s'", fInicio, fFin]).order(:date_start)
	end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company

	def self.names(idp)
		na = Project.find(idp)
		nam = na.name
	end
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :worker
  belongs_to :project
end

app/models/subconcept.rb
class Subconcept < ApplicationRecord
  belongs_to :concept
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :worker
end

app/models/user.rb
class User < ApplicationRecord
	has_one :worker
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  enum roles: [:user_default, :admin]
  after_initialize :set_default_roles, :if => :new_record?

  
  def set_default_roles
    self.roles ||= :user_default
  end

end

app/models/worker.rb
class Worker < ApplicationRecord
	belongs_to :user, optional: true
	has_attached_file :photo, styles:{thumb:"800x600", mini:"500x300"}
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

	def self.photos(idworker)
		pho = Worker.find(idworker)
		phot = pho.photo
	end

	def self.names(idworker)
		na = Worker.find(idworker)
		nam = na.name 
	end

end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :accesscontroller

  def accesscontroller
    if current_user.roles =="user_default"
      respond_to do |format|
          format.html {redirect_to welcome_index_path,notice: '' }
          format.js
      end
    end
  end


  # GET /concepts
  # GET /concepts.json
  def index
    @concepts = Concept.all

    @concepto =params[:commit]
    if @concepto
      @subs =Subconcept.select(:id,:name,:concept_id).where("subconcepts.concept_id"=>@concepto)
      if @subs.length == 0
        @subs = false
      end
    end
   # byebug
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(concept_params)

    respond_to do |format|
      if @concept.save
        format.html { redirect_to concepts_path, notice: 'Concept was successfully created.' }
        format.json { render :show, status: :created, location: @concept }
      else
        format.html { render :new }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1
  # PATCH/PUT /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to concepts_path, notice: 'Concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @concept }
      else
        format.html { render :edit }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept.destroy
    respond_to do |format|
      format.html { redirect_to concepts_url, notice: 'Concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_params
      params.require(:concept).permit(:name, :description, :type_concept)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/hour_helper.rb
module HourHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/concepts/_form.html.erb
<div style="width:50%">
  <%= form_for(concept) do |f| %>
    <% if concept.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

        <ul>
        <% concept.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :nombre %>
      <%= f.text_field :name, :class=>"form-control"  %>
    </div>
    <div>
      <%= f.label :tipo_concepto%>
      <%= f.select(:type_concept, options_for_select([['Seleccione...', "indefinido"], ['Viaticos', "viatico"], ['Administrativos', "administrativo"],]), {},:class=>"form-control" ) %>
    </div>
    <div class="field">
      <%= f.label :descripcion %>
      <%= f.text_area :description,:class=>"form-control"  %>
    </div>

    <div class="actions">
      <button class="btn btn-primary" type="submit" name="commit" value="Guardar"><i class="fa fa-floppy-o"></i> Guardar</button> 
    </div>
  <% end %>
</div>

app/views/concepts/edit.html.erb
<div style=" float:right; font-size:50px; margin:8px 20px;">
	<i class="fa fa-chevron-circle-left" aria-hidden="true" onclick="document.location='/concepts'" title="Regresar"></i>
</div>
<h1>Editar Concepto</h1>

<%= render 'form', concept: @concept %>

app/views/concepts/index.html.erb
<fieldset class="scheduler-border">
  <legend class="scheduler-border" style="width:auto">Conceptos</legend>

  <div class="table-responsive">
    <table class="uk-table uk-table-hover uk-table-striped">
      <thead>
        <tr>
          <th class="col-md-1"><h4>Nombre</h4></th>
          <th class="col-md-1"><h4>Tipo</h4></th>
          <th class="col-md-3"><h4>Descripcion</h4></th>
          <th class="col-md-3"></th>
          <th></th>
          <th class="col-md-1"><h5 style="color:#A4A4A4">Editar</h5></th>
          <th class="col-md-1"><h5 style="color:#A4A4A4">Eliminar</h5></th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @concepts.each do |concept| %>
          <tr>
            <td style="vertical-align:middle"><%= concept.name %></td>
            <td style="vertical-align:middle"><%= concept.type_concept %></td>
            <td style="vertical-align:middle"><%= concept.description %></td>

            <%= form_tag({:controller => "concepts", :action =>"index"}, :method => "get") do %>
              <td><button class="btn btn-primary" type="submit" name="commit" value="<%=concept.id%>"><i class="fa fa-th"></i> Subconceptos</button></td>
            <% end %>
            <td></td>

            <td class="col-md-1">
              <i class="fa fa-pencil-square-o" title="editar" style="font-size:30px; color:#A4A4A4" onclick="document.location='<%=edit_concept_path(concept)%>'"></i>
            </td>

            <td class="col-md-1">
              <a type="submit"  data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="editar" href="<%=concept_path(concept)%>" class="fa fa-trash-o" style="font-size:30px; float:left; color:#A4A4A4;" ></a>
            </td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<br>

<div style=" text-align:center; float:left">
  <h5> agregar concepto</h5>
  <i type="button" class="fa fa-plus-circle" style="font-size:45px; color:#01DF01" onclick="document.location='/concepts/new'"></i>
</div>
</fieldset>
<br><br>

<%if @subs%>
<fieldset class="scheduler-border">
<legend class="scheduler-border" style="width:auto">Subconcepto de <%= Concept.names(@concepto) %></legend>
  <div class="table-responsive">
    <table class="uk-table uk-table-hover uk-table-striped">
      <thead>
        <tr>
          <th><h4>index</h4></th>
          <th><h4>Subconcepto</h4></th>
        </tr>
      </thead>

      <tbody>
        <% @subs.each_with_index do |concept,index| %>
          <tr>
            <td><%= index %></td>
            <td><%= concept.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<% elsif @concepto and !@subs %>
  <h3>El concepto <i><%= Concept.names(@concepto) %></i> no tiene subconcepto</h3>
<%end%>

<%if @concepto%>

<div style="width:auto; text-align:center; float:left">
  <h5>agregar subconcepto</h5>
  <i type="button" class="fa fa-plus-circle" style="font-size:45px; color:#01DF01" onclick="document.location='/subconcepts/new'"></i>
</div>
<%end%>

</fieldset>

app/views/concepts/new.html.erb
<div style=" float:right; font-size:50px; margin:8px 20px;">
	<i class="fa fa-chevron-circle-left" aria-hidden="true" onclick="document.location='/concepts'" title="Regresar"></i>
</div>
<h1>Concepto Nuevo</h1>

<%= render 'form', concept: @concept %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @concept.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @concept.type_concept %>
</p>

<p>
  <strong>Description:</strong>
  <%= @concept.description %>
</p>

<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>