config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post 'users/index', to: "users#index"
  get 'users/approve/:iduser', to: "users#approve", as: 'approve'
  post 'users/approve/:iduser', to: "users#approve"

  devise_for :users
  resources :subconcepts
  get 'hour/index/:pro,:per', to: "hour#index", as: 'index'
  get 'periods_auto/index'
  get 'expenses/new/:per', to: "expenses#new", as: 'new_expense'

  resources :cards
  resources :workers
  resources :administrative_expenses
  resources :projects_users
  resources :expenses
  resources :concepts
  resources :periods
  resources :clients
  resources :tasks
  resources :projects
  resources :companies
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  post '/expenses/new/:per', to: "expenses#new"
  post '/hour/index/:pro,:per', to: "hour#index"
  post '/administrative_expenses/new', to: "administrative_expenses#new"
  post '/concepts', to: "concepts#index"


end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :worker
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/concept.rb
class Concept < ApplicationRecord
	
	enum type_concept: [:indefinido, :viatico, :administrativo]
    after_initialize :set_default_type_concept, :if => :new_record?

  
    def set_default_type_concept
    	self.type_concept ||= :indefinido
    end

	def self.names(idc)
		na = Concept.find(idc)
		nam = na.name 
	end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :period
  belongs_to :project
  belongs_to :concept
  belongs_to :worker

  enum payment_type: [:efectivo, :tarjeta]
  after_initialize :set_default_payment_type, :if => :new_record?

  
  def set_default_payment_type
    self.payment_type ||= :efectivo
  end

  def self.dia_mes(fecha)
  	dia = fecha.cwday
  	if dia == 1
  		day = "Lun"
  	elsif dia == 2
  		day = "Mar"
	  elsif dia == 3
  		day = "Mie"
	  elsif dia == 4
  		day = "Jue"
	  elsif dia == 5
  		day = "Vie"
	  elsif dia == 6
  		day = "Sab"
	  elsif dia == 7
  		day = "Dom"
  	end
  	return day	
  end

  def self.checked(x,y)
    if x == y
      return :checked
    end
  end

end

app/models/hours_project.rb
class HoursProject < ApplicationRecord
  belongs_to :worker
  belongs_to :period
  belongs_to :project


  def self.hours_day(idw,ppe,proy,day)
  	horareg = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>ppe,"hours_projects.project_id"=>proy,"hours_projects.worker_id"=>idw) 
    hl = horareg.length
    for i in 0..hl-1 do
    	fecha = horareg[i].day
    	if fecha.cwday==day
    		cons = HoursProject.find_by(period_id:ppe,project_id:proy,day:fecha,worker_id:idw)
    		res = cons.hours
    	end
    end
    return res		
  end

  def self.hours_total(proy,per)
    horatot = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>per,"hours_projects.project_id"=>proy) 
    total = horatot.sum(:hours)
  end

  def self.periods_total(proy)
    pertot = HoursProject.select(:period_id).distinct.where("hours_projects.project_id"=>proy)
    pertot.count(:period_id)
  end

  def self.hours_id(idw,ppe,proy,day)
    horareg = HoursProject.select(:id,:day,:hours).where("hours_projects.period_id"=>ppe,"hours_projects.project_id"=>proy,"hours_projects.worker_id"=>idw) 
    hl = horareg.length
    for i in 0..hl-1 do
      fecha = horareg[i].day
      if fecha.cwday==day
        cons = HoursProject.find_by(period_id:ppe,project_id:proy,day:fecha,worker_id:idw)
        res = cons.id
      end
    end
    return res    
  end
end

app/models/period.rb
class Period < ApplicationRecord

	def self.periodo(per)
		perinf = Period.find(per)
		"#{perinf.date_start.strftime("%v")} "  " al "  " #{perinf.date_end.strftime("%v")}"
	end

	def periodosAnual
    	Period.order(:date_start).find_by(year: 2016)
	end
  	def periodoRango
	    fInicio = Date.strptime("#{date_start}", "%Y-%m-%d")
	    fIni = fInicio.to_formatted_s(:short)
	    fFinal = Date.strptime("#{date_end}", "%Y-%m-%d")
	    fFin = fFinal.to_formatted_s(:short)
	    "#{fIni} - #{fFin}"
  	end

    def self.periodosAnualCombo
	  	fInicio = Time.now - 2.month
	  	fFin 	= Time.now
	  	Period.where(["date_start >= '%s' and date_end <= '%s'", fInicio, fFin]).order(:date_start)
	end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company

	def self.names(idp)
		na = Project.find(idp)
		nam = na.name
	end
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :worker
  belongs_to :project
end

app/models/subconcept.rb
class Subconcept < ApplicationRecord
  belongs_to :concept
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :worker
end

app/models/user.rb
class User < ApplicationRecord
	has_one :worker
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  enum roles: [:user_default, :admin]
  after_initialize :set_default_roles, :if => :new_record?

  
  def set_default_roles
    self.roles ||= :user_default
  end

end

app/models/worker.rb
class Worker < ApplicationRecord
	belongs_to :user, optional: true
	has_attached_file :photo, styles:{thumb:"800x600", mini:"500x300"}
	
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

	def self.photos(idworker)
		pho = Worker.find(idworker)
		phot = pho.photo
	end

	def self.names(idworker)
		na = Worker.find(idworker)
		nam = na.name 
	end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :accesscontroller

  def accesscontroller
    if current_user.roles =="user_default"
      respond_to do |format|
          format.html {redirect_to welcome_index_path,notice: '' }
          format.js
      end
    end
  end

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_path, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_path, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:number, :worker_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/hour_helper.rb
module HourHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/cards/_form.html.erb
  <div style="width:50%">
  <%= form_for(card) do |f| %>
    <% if card.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

        <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :numero %>
      <%= f.number_field :number, :class=>"form-control" %>
    </div>

    <div class="field">
      <%= f.label :trabajador %>
      <%= collection_select( :card, :worker_id, Worker.all, :id, :name,{prompt: "Selecciona al trabajador", :multiple => false}, :class=>'form-control') %>
    </div> 

    <div class="actions">
      <button class="btn btn-primary" type="submit" name="commit" value="Guardar"><i class="fa fa-floppy-o"></i> Guardar</button> 
    </div>
  <% end %>
</div>

app/views/cards/edit.html.erb
<div style=" float:right; font-size:50px; margin:8px 20px;">
	<i class="fa fa-chevron-circle-left" aria-hidden="true" onclick="document.location='/cards'" title="Regresar"></i>
</div>

<h1>Editar Tarjeta</h1>

<%= render 'form', card: @card %>

app/views/cards/index.html.erb
<fieldset class="scheduler-border">
<legend class="scheduler-border" style="width:auto;">Tarjetas</legend>
    <table id="example" class="uk-table uk-table-hover uk-table-striped" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Numero</th>
          <th>Trabajador</th>
          <th>Editar</th>
        </tr>
      </thead>

      <tbody style="text-transform: lowercase;">
        <% @cards.each do |card| %>
          <tr>
            <td style="vertical-align:middle"><%= card.number %></td>
            <td style="vertical-align:middle"><%= card.worker.name %></td>
            <td style="vertical-align:middle"><i class="fa fa-pencil-square-o" title="editar" style="font-size:25px; color:#A4A4A4" onclick="document.location='<%=edit_card_path(card)%>'"></i></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
        
    <button class="btn btn-primary" onclick="document.location='/cards/new'"><i class="fa fa-plus-circle" style="color:skyblue"></i> Agregar</button>
</fieldset>




<script type="text/javascript" src="//code.jquery.com/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/dataTables.uikit.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

app/views/cards/new.html.erb
<div style=" float:right; font-size:50px; margin:8px 20px;">
	<i class="fa fa-chevron-circle-left" aria-hidden="true" onclick="document.location='/cards'" title="Regresar"></i>
</div>

<h1>Nueva Tarjeta</h1>

<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @card.number %>
</p>

<p>
  <strong>Worker:</strong>
  <%= @card.worker %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>