config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post 'users/index', to: "users#index"
  get 'users/approve/:iduser', to: "users#approve", as: 'approve'
  post 'users/approve/:iduser', to: "users#approve"

  devise_for :users
  resources :subconcepts
  get 'hour/index/:pro,:per', to: "hour#index", as: 'index'
  get 'periods_auto/index'
  get 'expenses/new/:per', to: "expenses#new", as: 'new_expense'

  resources :cards
  resources :workers
  resources :administrative_expenses
  resources :projects_users
  resources :expenses
  resources :concepts
  resources :periods
  resources :clients
  resources :tasks
  resources :projects
  resources :companies
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#index'
  post '/expenses/new/:per', to: "expenses#new"
  post '/hour/index/:pro,:per', to: "hour#index"
  post '/administrative_expenses/new', to: "administrative_expenses#new"
  post '/concepts', to: "concepts#index"


end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  

  # GET /expenses
  # GET /expenses.json
  def index
    @expense = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new 
    @expense = Expense.new
    @concept = Concept.select(:id,:name).where("concepts.type_concept"=>1)

    @periodos = Period.periodosAnualCombo
    @pro = nil
    @wor = nil
    @per = params[:per]
    @pernext = @per.to_i + 1
    @perbefore = @per.to_i - 1 
    if params[:expense]
      @dia = params[:x]
      @pro = params[:expense][:project_id]
      @con = params[:expense][:concept_id]
      if @con == nil
        @con = params[:concept]
      end
      @wor = params[:worker_id]
      @mon = params[:Monto]
      @tip = params[:tipo_pago]
      @com = params[:commit]
      xml = params[:xml]
      pdf = params[:pdf]
      ticket = params[:ticket]
      card = params[:expense][:card]
      des = params[:Descripcion]
      rem = params[:Reembolsable] 
      subtot = params[:Subtotal]
      subcon = params[:expense][:subconcept_id]
      iva = params[:Impuesto]
    end
    @subconcepts = Subconcept.select(:id,:name).where("subconcepts.concept_id"=>@con)
    if @per
      period = Period.find(@per)
      diaini = period.date_start
      diafin = period.date_end
      @arrdia = []
      while diaini <=diafin
        @arrdia << diaini
        diaini+=1
      end
    end 
    if @pro 
      @resp1 = true 
      pw = HoursProject.select(:worker_id).distinct.where("hours_projects.project_id"=>@pro,"hours_projects.period_id"=>@per)
      @arrpw = []
      pw.each do |w|
        @arrpw << Worker.find(w.worker_id)
      end
    end
    if @tip
      @resp2 = true
      if @tip == 'tarjeta'
        @resp3 = true 
        @tarjetas = Card.select(:id,:number,:worker_id).where("cards.worker_id"=> @wor)

      end
    end 
    if @com == "1"
      if !rem
        rem = "no"
      end
      worin = ""
      ind = 0
      for i in 0..pw.length-1 do
        par = ":r"+i.to_s
        no = params[par.parameterize.underscore.to_sym]
        if ind == 0
          esp = ""
        else
          esp = ", "
        end
        if no
          worin = worin + esp + no.to_s
          ind += 1
        end
      end 
      expins = Expense.new(:period_id => @per,:project_id => @pro, :concept_id => @con,:worker_id => @wor, :mount => @mon, :payment_type => @tip,:card =>card, :day =>@dia,:xml_file =>xml, :pdf_file=>pdf, :ticket=>ticket, :refundable=>rem, :description=>des, :workers_in=>worin, :subtotal=>subtot, :vat=>iva, :subconcept_id=>subcon ) 
      expins.save
      respond_to do |format|
        format.html {redirect_to new_expense_path(@per),notice: 'Gasto Guardado' }
        format.js
      end
      byebug
    end 
     #byebug
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create 
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end 
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:period_id, :project_id, :concept_id, :mount, :worker_id, :xml_file, :pdf_file, :ticket, :card, :payment_type,:day)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<div style="width:50%">
<%= form_for(expense) do |f| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :period_id %>
    <%= collection_select( :expense, :period_id, Period.all, :id, :date_start,{prompt: "Selecciona perido", :multiple => false}, :class=>"form-control") %>
  </div>

  <div class="field">
    <%= f.label :project_id %>
    <%= collection_select( :expense, :project_id, Project.all, :id, :name,{prompt: "Selecciona proyecto", :multiple => false}, :class=>"form-control") %>
  </div>

  <div class="field">
    <%= f.label :concept_id %>
    <%= collection_select( :expense, :concept_id, Concept.all, :id, :name,{prompt: "Selecciona concepto", :multiple => false}, :class=>"form-control") %>
  </div>

  <div class="field">
    <%= f.label :mount %>
    <%= f.text_field :mount, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :worker_id %>
    <%= collection_select( :expense, :worker_id, Worker.all, :id, :name,{prompt: "Selecciona el empleado", :multiple => false}, :class=>"form-control") %>
  </div>


  <div class="field">
    <%= f.label :payment_type %>
    <%= f.select(:payment_type, options_for_select([['Efectivo', 'efectivo'], ['Tarjeta', 'tarjeta']]), {},:class=>"form-control") %>
  </div>

  <div class="field">
    <%= f.label :card %>
    <%= f.text_field :card, :class=>"form-control" %>
  </div>
  
  <div class="field">
    <%= f.label :xml_file %>
    <%= f.text_field :xml_file, :class=>"form-control" %>
  </div>
  

  <div class="field">
    <%= f.label :pdf_file %>
    <%= f.text_field :pdf_file, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :ticket %>
    <%= f.text_field :ticket, :class=>"form-control" %>
  </div>

  <div class="actions">
    <button class="btn btn-primary" type="submit" name="commit" value="Guardar"><i class="fa fa-floppy-o"></i> Guardar</button> 
  </div>
<% end %>
</div>

app/views/expenses/edit.html.erb
<div style=" float:right; font-size:50px; margin:8px 20px;">
	<i class="fa fa-chevron-circle-left" aria-hidden="true" onclick="document.location='/expenses'" title="Regresar"></i>
</div>

<h1>Editar Viatico</h1>

<%= render 'form', expense: @expense %>

app/views/expenses/index.html.erb
<fieldset class="scheduler-border">
<legend class="scheduler-border" style="width:auto;">Proyectos</legend>
  <table id="example" class="uk-table uk-table-hover uk-table-striped" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Proyecto</th>
          <th>Concepto</th>
          <th>Monto</th>
          <th>Trabajador</th>
          <th>Tipo de pago</th>
          <th>Tarjeta</th>
          <th>Xml</th>
          <th>Pdf</th>
          <th>Ticket</th>
          <th>Editar</th>
        </tr>
      </thead>
      <tbody style="text-transform: lowercase;">
      <% @expense.each do |expense| %>
        <tr>
          <td style="vertical-align:middle"><%= expense.period_id %></td>
          <td style="vertical-align:middle"><%= expense.project.name %></td>
          <td style="vertical-align:middle"><%= expense.concept.name %></td>
          <td style="vertical-align:middle"><%= expense.mount %></td>
          <td style="vertical-align:middle"><%= expense.worker.name%></td>
          <td style="vertical-align:middle"><%= expense.payment_type %></td>
          <td style="vertical-align:middle"><%= expense.card %></td>
          <td style="vertical-align:middle"><%= expense.xml_file %></td>
          <td style="vertical-align:middle"><%= expense.pdf_file %></td>
          <td style="vertical-align:middle"><%= expense.ticket %></td>
          <td style="vertical-align:middle"><i class="fa fa-pencil-square-o" title="editar" style="font-size:25px; color:#A4A4A4" onclick="document.location='<%=edit_expense_path(expense)%>'"></i></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>

  <button class="btn btn-primary" onclick="document.location='/projects/new'"><i class="fa fa-plus-circle" style="color:skyblue"></i> Agregar</button>

</fieldset>

<script type="text/javascript" src="//code.jquery.com/jquery-1.12.3.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/dataTables.uikit.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

app/views/expenses/new.html.erb
<style type="text/css">
	hr.style-two {
    border: 0;
    height: 1px;
    background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0));
	}

  	#dias {
  		background-color: #0099cc;
  	}
  	#dias  input[type="radio"] + i.glyphicon {         
    	opacity: 0;
  	}

  	#dias  input[type="radio"]:checked + i.glyphicon {        
    	opacity: 1;
    	color:white;       
	}

	#cargo.btn.active  input[type="radio"] + span.glyphicon {         
    	opacity: 0;       
  	}
  	#cargo.btn input[type="radio"]:checked + span.glyphicon {        
    	opacity: 1;       
	}

	#reembolso.btn2  input[type="checkbox"]:not(:checked) + span.glyphicon {         
    	opacity: 0;       
  	}
  	#reembolso.btn2.active  input[type="checkbox"]:checked + span.glyphicon {        
    	opacity: 1;       
	}

	#inmiscuidos.btn  input[type="checkbox"]:not(:checked) + span.glyphicon {         
    	opacity: 0;       
  	}
  	#inmiscuidos.btn.active  input[type="checkbox"]:checked + span.glyphicon {        
    	opacity: 1;       
	}

	a:hover {
        background-color: transparent;
        opacity:0.5;
    }

    .btn.active, .btn:active {
    background-image: none;
    outline: 0;
    /* -webkit-box-shadow: inset 0 3px 5px rgba(0,0,0,.125); */
    box-shadow: inset 0 0px 0px rgba(0,0,0,0);
	}
</style>

<%= form_tag(:controller => "expenses", :action => "new",  method: "post" )  do %>

	<div align="center">
		<div class="group">
				<h3>Periodo: </h3>
				<label style="height:70px; width:600px; border-radius:35px; padding:0px 5px 0px 4px; background-color:#2e353d;">
					<div align="center" style="width:100%;">
						<div style="width:10%; float:left;">
						<%= link_to new_expense_path(@perbefore), :style=>"color:white;font-size:30px" do %>
							<i class="fa fa-chevron-circle-left" style="font-size:71px;"></i>
						<%end%> 
					</div>

					<div style="width:80%; float:left">
						<h2 style="color:white;padding-top:20px"><%= Period.periodo(@per)%></h2>
					</div>

					<div style="width:10%; float:left">
						<%= link_to  new_expense_path(@pernext), :style=>"color:white;font-size:30px" do %>
							<i class="fa fa-chevron-circle-right" style="font-size:71px;"></i> 
						<%end%>
					</div>
				</div>
			</label>
		</div>
	</div>

	<br><br>

	<%if !@resp1%>
	<div align="center">
		<div class="field"  style="width:auto">
		  	<h3 style="width:auto">Selecciona el dia del gasto</h3> 
		  	<label style="border-top: solid 0px grey; border-bottom: solid 0px grey; width:900px;">
				<% @arrdia.each do |x|%>
					<div id="div-dias" class="btn-group" data-toggle="buttons">
					   	<label id="dias" class="btn btn-default active" style="width:100px; height:100px; text-align:center; border-radius:0px;background-color:#EDEDED;outline:0;">
							<h4 style="color:grey"><%=Expense.dia_mes(x)%></h4>
							<%= radio_button_tag :x,x, :style=>'float:left;' %>
						  	<i class="glyphicon glyphicon-ok" style=" font-size:20px;color:grey;"></i>
						  	<h6 style="margin-bottom: 0px;margin-top: 10px; color:grey"><%= x.strftime('%v')%></h6>
						</label>
					</div>
				<%end%>
			</label>
		</div>
	</div>

		<br>
	
	<%elsif @resp1%>
		<div class="field"  style="width:auto">
		  	<legend class="schedule-border" style="width:auto">Dia del gasto</legend> 
			<div class="btn-group" data-toggle="buttons">
				<label class="btn btn-primary active" style="width:100px; height:100px; text-align:center; border-radius:0px 0px 0px 0px; background-color:#EDEDED; z-index:0;">
					<h4 style="color:grey"><%= Expense.dia_mes(Date.parse(@dia).strftime("%a, %d %b %Y").to_date)%></h4>
					<%= radio_button_tag :x,@dia, :style=>'float:left;' %>
					<span class="glyphicon glyphicon-ok" style=" font-size:20px; color:grey"></span>
					<h6 style="color:grey; margin-bottom: 0px;margin-top: 10px;"><%= Date.parse(@dia).strftime('%v')%></h6>
				</label>
			</div>
		</div>

		<br>

	<%end%>

	<div class="field" style="width:500px">
	    <h6>Proyecto:</h6>
	    <%= collection_select( :expense, :project_id, Project.all, :id, :name,{prompt: "Selecciona proyecto", :selected => @pro, :multiple => false},:required => "required",:class=>"form-control") %>
 	</div>

 	<br>
	
	 	<%if @resp1 %>
	 		<% if @arrpw.length != 0%>
				<%if !@resp2%>
					<div class="field">
					  	<fieldset class="scheduler-border">
					  		<legend class="scheduler-border" style="width:auto"> Cargo a </legend>
        					<% @arrpw.each do |x|%>
        				    	<div class="btn-group" data-toggle="buttons">
        				    		<label id="cargo" class="btn btn-default active" style="width:150px;height:150px; border-radius:60px 6px 6px 6px; outline:0;">
        				    			<%= image_tag(x.photo.url(:mini), :style=>'float:left;margin-top:5px;margin-bottom:5px;border-radius: 50%;overflow: hidden;width:100px;height:100px')%><br>
        				    			<%= radio_button_tag :worker_id, x.id, :style=>'float:left;display:none;' %>
        				    			<span class="glyphicon glyphicon-ok-sign" style="float:right; font-size:20px"></span>
        				    			<label for="<%x%>" style="margin-top: 0px;border-bottom-width: 0px; float:left;color:grey">
        				    				<%=x.name%>
        				    			</label>
        				    		</label>
        				    	</div>
        					<%end%>
						</fieldset>
					</div>

					<br>
					
					<div class="field" style="width:500px" >
					    <h6>Tipo de pago :</h6>
					    <select name="tipo_pago" class="form-control" >
					    <option value="efectivo">Efectivo</option>
					    <option value="tarjeta">Tarjeta</option>
					    </select>
					</div>

					<div class="field" style="width:500px">
				    <h6>Concepto:</h6>
				    <%= collection_select( :expense, :concept_id, @concept, :id, :name,{prompt: "Selecciona concepto", :selected => @con,:multiple => false},:class=>"form-control",:required => "required") %>
					</div>

					<br>

				<%end %>
			<%else%>
				<h3>No hay personas asignadas a este proyecto dentro este periodo</h3>
			<% end %>
			<%if @resp2%>
			  	<label for="" class="btn btn-primary active" style="width:150px; height:150px; border-radius:60px 6px 6px 6px;">
			  		<%= image_tag(Worker.photos(@wor).url(:mini), :style=>'float:left;margin-top:5px;margin-bottom:5px;border-radius: 50%;overflow: hidden;width:100px;height:100px')%><br>
			  		<label style="margin-top: 0px;border-bottom-width: 0px; float:left">
			  		<%=Worker.names(@wor)%>
			  		</label>
			  	</label>

			  	<br>
				
				<%= hidden_field_tag "worker_id", @wor%>
				<%= hidden_field_tag "tipo_pago", @tip%>
				<%= hidden_field_tag "concept", @con%>
		
				<%if @resp3 %>
				
				<br>

				<div class="field" style="width:500px">
						<h6>Selecciona tarjeta a la que se hizo el cargo :</h6>
					    <%= collection_select( :expense, :card, @tarjetas, :id, :number,{prompt: "Selecciona tarjeta", :multiple => false},:class=>"form-control",:required => "required") %>
					</div>
				<%end%>

			  	<br>
			  	<br>

			  	<div style="width:100%">
				  	<div class="field" style="width:48%; float:left;">
					    <h6>Concepto:</h6>
					    <%= collection_select( :expense, :concept_id, @concept, :id, :name,{prompt: "Selecciona concepto", :selected => @con,:multiple => false},:class=>"form-control",:disabled=>true) %>
					</div>

				  	<%if @subconcepts.length>0%>	
						<div class="field" style="width:48%; float:right;">
						    <h6>Suboncepto:</h6>
						    <%= collection_select( :expense, :subconcept_id, @subconcepts, :id, :name,{prompt: "Selecciona subconcepto", :selected => nil,:multiple => false},:class=>"form-control",:required => "required") %>
						</div>
					<%end %>
				</div>

				<fieldset class="scheduler-border" style="width:100%">
					<legend class="scheduler-border" style="width:auto"> Detalles </legend>
						<div class="field" style="width:23%; float:left; margin-right:15px;">
						    <h6>Total:</h6>
						    <%= number_field_tag "Monto", @mon,:placeholder => "0.00",step: :any,:class=>"form-control",:required => "required"%>
						</div>

						<div class="field" style="width:23%; float:left; margin-right:15px;">
						    <h6>Subtotal:</h6>
						    <%= number_field_tag "Subtotal", nil,:placeholder => "0.00",step: :any,:class=>"form-control",:required => "required"%>
						</div>

						<div class="field" style="width:23%; float:left; margin-right:15px;">
						    <h6>Impuesto:</h6>
						    <%= number_field_tag "Impuesto", nil,:placeholder => "0.00",step: :any,:class=>"form-control",:required => "required"%>
						</div>

						<div class="field" style="width:23%; float:left;">
						    <h6>Reembolsable:</h6>
						    <label id="reembolso" class="btn2 btn-primary active" style="width:32px;height:32px;text-align:center;">
							    	<%= check_box_tag "Reembolsable","si", false, :style=>'display:none;' %>
							    	<span class="glyphicon glyphicon-ok" style="font-size:15px; padding-top:8px; z-index:0;"></span>
						    </label>
						</div>

						<br>

						<div class="field" style="width:500px">
						    <h6>Descripcion:</h6>
						    <%= text_area_tag "Descripcion", nil, rows: 5, col: 25,:class=>"form-control",:required => "required"%>
						</div>
				</fieldset>  

					<div class="field">
					  	<fieldset class="scheduler-border" style="width:100%">
					  		<legend class="scheduler-border" style="width:auto">Trabajadores Inmisciudos</legend>
						  	<% @arrpw.each_with_index do |x,index|%>
							  	<div class="btn-group">
	    				    		<label id="inmiscuidos" class="btn btn-default active" style="width:150px; height:150px; border-radius:60px 6px 6px 6px; z-index:0;">
							  			<%= image_tag(x.photo.url(:mini), :style=>'border: 2px;float:left;margin-top:5px;margin-bottom:5px;border-radius: 50%;overflow: hidden;width:100px;height:100px')%><br>
							  			<%= check_box_tag "r"+index.to_s, x.name+" "+x.last_name+" "+x.mothers_last_name, false, :style=>'display:none'%>
							  			<span class="glyphicon glyphicon-ok-sign" style="float:right; font-size:20px"></span>
							  			<label for="<%x%>" style="margin-top: 0px;border-bottom-width: 0px; float:left">
	    				    				<%=x.name%>
	    				    			</label>
							  		</label>
							  	</div>
						  	<%end%>
						</fieldset>
					</div>

					<br>

		  		<div class="field" align="center">
			  		<div style="width:500px">
					    <div class="custom-input-file" style="width:150px;float:left;margin-right:10px">
					 		<h6>xml</h6>
					    	<%= file_field_tag "xml",:class=>"input-file" %>
					    	<div class="archivo">...</div>
					    </div>
					  
					    <div class="custom-input-file" style="width:150px;float:left;margin-right:10px">
					    	<h6>pdf</h6>
					    	<%= file_field_tag "pdf",:class=>"input-file" %>
					    	<div class="archivo">...</div>
					    </div>

					    <div class="custom-input-file" style="width:150px;float:left;margin-right:10px">
					    	<h6>ticket</h6>
					    	<%= file_field_tag "ticket",:class=>"input-file" %>
					    	<div class="archivo">...</div>
					    </div>
				    </div>
			    </div>

			    <br>
			    <br>
			    <br>

			    <div class="field" align="center">
			    	<button type="submit" name="commit" value="1" class="btn3 btn-success" style="margin-top:30px;margin-bottom:60px;"><i class="fa fa-floppy-o"></i> Guardar</button> 
			    </div>
			<%end%>
		<%end %>
	
	<% if @resp2%>
		<%else%>
			<div align="left">
				<br><button type="submit" name="commit" value="3" class="btn btn-primary" >Cargar informacion</button>
			</div>
		<% end %> 
<%end%>


<script type="text/javascript">
	$(function(){
	    $(".custom-input-file input:file").change(function(){
	        $(this).parent().find(".archivo").html($(this).val());
	    }).css('border-width',function(){
	        if(navigator.appName == "Microsoft Internet Explorer")
	            return 0;
	    });
	});
</script>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Period:</strong>
  <%= @expense.period.date_start %>
</p>

<p>
  <strong>Project:</strong>
  <%= @expense.project.name %>
</p>

<p>
  <strong>Concept:</strong>
  <%= @expense.concept.name %>
</p>

<p>
  <strong>Mount:</strong>
  <%= @expense.mount %>
</p>

<p>
  <strong>User:</strong>
  <%= @expense.worker_id %>
</p>

<p>
  <strong>Xml file:</strong>
  <%= @expense.xml_file %>
</p>

<p>
  <strong>Pdf file:</strong>
  <%= @expense.pdf_file %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @expense.ticket %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>